In [23]:
l = [23241, 456, 29, 112, -482]

In [2]:
l

[23241, 456, 29, 112, -482]

In [3]:
import numpy as np

In [24]:
a = np.array(l)

In [25]:
a

array([23241,   456,    29,   112,  -482])

In [8]:
b = np.array([12, 455, 63.3, True, "abc"])

In [9]:
b

array(['12', '455', '63.3', 'True', 'abc'],
      dtype='<U32')

In [10]:
print(b)

['12' '455' '63.3' 'True' 'abc']


In [11]:
l.pop()

-482

In [12]:
l

[23241, 456, 29, 112]

In [13]:
a.mean()

4671.1999999999998

-------

In [14]:
#slicing arrays

In [26]:
l[1:]

[456, 29, 112, -482]

In [27]:
a

array([23241,   456,    29,   112,  -482])

In [28]:
a[2:]

array([  29,  112, -482])

In [30]:
b = a[2:4] #still a, not another array

In [31]:
b

array([ 29, 112])

In [32]:
b[0]

29

In [33]:
b[:] = 111

In [34]:
b

array([111, 111])

In [35]:
a

array([23241,   456,   111,   111,  -482])

In [36]:
c = a.copy() #create a copy of a

In [37]:
c

array([23241,   456,   111,   111,  -482])